apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-api
  template:
    metadata:
      labels:
        app: node-js-api
    spec:
      containers:
      - name: node-js-api
        image: graju9986/node-js-api:latest
        ports:
        - containerPort: 3000

